config/routes.rb
Rails.application.routes.draw do
  resources :events, param: :slug
  devise_for :members
  use_doorkeeper
  resources :participants
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'participants#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, presence: true
  # slug is required, unique and something that might be in an URL path
  validates :slug, presence: true, format: { with: /\A[\p{Word}-]+\z/ }, uniqueness: { case_sensitive: false }, exclusion: { in: %w(new) }

  # use slug for URL generation
  def to_param
    slug
  end
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/participant.rb
class Participant < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find_by(slug: params[:slug])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :slug, :body, :registration_from, :registration_to)
    end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: [:show, :edit, :update, :destroy]

  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
        format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to participants_url, notice: 'Participant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_params
      params.require(:participant).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
= simple_form_for @event do |f|
  .row
    = f.input :title
  .row
    = f.input :slug
  .row
    = f.input :body
  .row
    = f.input :registration_from, as: :datetime, html5: :true,
        wrapper_html: { class: 'small-6' }
    = f.input :registration_to, as: :datetime, html5: :true,
        wrapper_html: { class: 'small-6' }
  .row
    .columns
      = f.button :submit, class: 'success'

app/views/events/edit.html.haml
%h1 Editing event

= render 'form'

= link_to 'Show', @event, class: 'button'
= link_to 'Back', events_path, class: 'button secondary'

app/views/events/index.html.haml
%h1 Events

%table
  %thead
    %tr
      %th Title
      %th Slug
      %th From
      %th To
      %th

  %tbody
    - @events.each do |event|
      %tr
        %td= link_to event.title, event
        %td= event.slug
        %td= event.registration_from
        %td= event.registration_to
        %td.button-group.small
          = link_to 'Edit', edit_event_path(event), class: 'button hollow'
          = link_to 'Destroy', event, :method => :delete,
              :data => { :confirm => 'Are you sure?' },
              class: 'button hollow alert'

%br

= link_to 'New Event', new_event_path, class: 'button success'

app/views/events/new.html.haml
%h1 New event

= render 'form'

= link_to 'Back', events_path, class: 'button secondary'

app/views/events/show.html.haml
%h1= @event.title

%p
  %b Body:
  = @event.body
%p
  %b Registration from:
  = @event.registration_from
%p
  %b Registration to:
  = @event.registration_to

= link_to 'Edit', edit_event_path(@event), class: 'button success'
= link_to 'Back', events_path, class: 'button secondary'

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "de" }
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : "Anmelder"

    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tag

  %body
    =# we need the row class so that foundation can recognize inner rows
    .outer-container.row
      .inner-container.column

        - if notice
          .callout.success{ data: { closable: true } }
            %button.close-button{ data: { close: true } }
              %span &times;
            %p= notice

        = yield

app/views/participants/_form.html.haml
= form_for @participant do |f|
  - if @participant.errors.any?
    #error_explanation
      %h2= "#{pluralize(@participant.errors.count, "error")} prohibited this participant from being saved:"
      %ul
        - @participant.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :password
    = f.text_field :password
  .actions
    = f.submit 'Save'

app/views/participants/edit.html.haml
%h1 Editing participant

= render 'form'

= link_to 'Show', @participant
\|
= link_to 'Back', participants_path

app/views/participants/index.html.haml
%h1 Listing participants

%table
  %thead
    %tr
      %th Name
      %th Password
      %th
      %th
      %th

  %tbody
    - @participants.each do |participant|
      %tr
        %td= participant.name
        %td= participant.password
        %td= link_to 'Show', participant
        %td= link_to 'Edit', edit_participant_path(participant)
        %td= link_to 'Destroy', participant, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Participant', new_participant_path

app/views/participants/new.html.haml
%h1 New participant

= render 'form'

= link_to 'Back', participants_path

app/views/participants/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @participant.name
%p
  %b Password:
  = @participant.password

= link_to 'Edit', edit_participant_path(@participant)
\|
= link_to 'Back', participants_path